[package]
name = "bevy-inspector"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
bevy-inspector-derive = { path = "./bevy-inspector-derive" }
bevy = "0.1"

crossbeam-channel = "0.4"
tiny_http = "0.7"
webbrowser = "0.5"

[profile.dev.package."*"]
opt-level = 2
